services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: mohit_razorpay_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autoreconcile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d autoreconcile"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
